version: '2'
services:
  mongo_user_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/user/data
  pg_book_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=books
  userapp:
    restart: always
    build: user/
    ports:
      - "3001:3000"
    links:
      - mongo_user_db
  bookapp:
    restart: always
    build: book/
    ports:
      - "3002:3000"
    links:
      - pg_book_db